name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
#    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
# modified token
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#                    echo '![](./plot.png "Confusion Matrix")' >> report.md
#                   cml comment create report.md
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png
          # Create CML report
          cat metrics.txt >> report.md
          plotfile="$(ls -l plot.png)"
          echo "$plotfile" >> report.md
          echo "$(pwd)" >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          body="$(cat report.md)"
        path: plot.png
        path: report.md
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with: 
          sha: ${{ github.sha }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [commit-comment][1]
            ![confusion matrix](./plot.png)
      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: 1
      #     # body: |
      #     #   This is a multi-line test comment, test issue #1
      #     #   - With GitHub **Markdown** :sparkles:
      #     #   - Created by [create-or-update-comment][1]

      #     #   [1]: https://github.com/peter-evans/create-or-update-comment
      #     reactions: '+1'
      #     body-path: report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}